"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-09 08:48:27.717995
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('assumption_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('values', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'name')
    )
    op.create_index(op.f('ix_assumption_profiles_owner_id'), 'assumption_profiles', ['owner_id'], unique=False)
    op.create_table('comparisons',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('assumptions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comparisons_owner_id'), 'comparisons', ['owner_id'], unique=False)
    op.create_table('data_imports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('rows_total', sa.Integer(), nullable=False),
    sa.Column('rows_imported', sa.Integer(), nullable=False),
    sa.Column('rows_rejected', sa.Integer(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.Column('source_name', sa.String(length=200), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('licence', sa.String(length=200), nullable=True),
    sa.Column('attribution', sa.Text(), nullable=True),
    sa.Column('data_from', sa.Date(), nullable=True),
    sa.Column('data_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_imports_owner_id'), 'data_imports', ['owner_id'], unique=False)
    op.create_table('watchlists',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'name')
    )
    op.create_index(op.f('ix_watchlists_owner_id'), 'watchlists', ['owner_id'], unique=False)
    op.create_table('price_paid_transactions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.String(length=38), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('date_of_transfer', sa.Date(), nullable=False),
    sa.Column('postcode', sa.String(length=10), nullable=True),
    sa.Column('postcode_district', sa.String(length=5), nullable=True),
    sa.Column('postcode_sector', sa.String(length=7), nullable=True),
    sa.Column('property_type', sa.String(length=1), nullable=False),
    sa.Column('new_build', sa.Boolean(), nullable=False),
    sa.Column('tenure', sa.String(length=1), nullable=False),
    sa.Column('paon', sa.String(length=120), nullable=False),
    sa.Column('saon', sa.String(length=120), nullable=False),
    sa.Column('street', sa.String(length=120), nullable=False),
    sa.Column('locality', sa.String(length=120), nullable=False),
    sa.Column('town', sa.String(length=120), nullable=False),
    sa.Column('local_authority', sa.String(length=120), nullable=False),
    sa.Column('county', sa.String(length=120), nullable=False),
    sa.Column('ppd_category', sa.String(length=1), nullable=False),
    sa.Column('import_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['import_id'], ['data_imports.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_index('ix_ppd_district_date', 'price_paid_transactions', ['postcode_district', 'date_of_transfer'], unique=False)
    op.create_index('ix_ppd_local_authority', 'price_paid_transactions', ['local_authority'], unique=False)
    op.create_index('ix_ppd_sector_date', 'price_paid_transactions', ['postcode_sector', 'date_of_transfer'], unique=False)
    op.create_index(op.f('ix_price_paid_transactions_date_of_transfer'), 'price_paid_transactions', ['date_of_transfer'], unique=False)
    op.create_table('properties',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('address_line', sa.String(length=300), nullable=False),
    sa.Column('town', sa.String(length=120), nullable=False),
    sa.Column('postcode', sa.String(length=10), nullable=True),
    sa.Column('region', sa.String(length=20), nullable=False),
    sa.Column('property_type', sa.String(length=20), nullable=False),
    sa.Column('tenure', sa.String(length=20), nullable=False),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Integer(), nullable=True),
    sa.Column('floor_area_sqm', sa.Float(), nullable=True),
    sa.Column('asking_price', sa.Float(), nullable=False),
    sa.Column('estimated_monthly_rent', sa.Float(), nullable=False),
    sa.Column('rent_source', sa.String(length=30), nullable=False),
    sa.Column('listing_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('data_source', sa.String(length=20), nullable=False),
    sa.Column('import_id', sa.Uuid(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('assumption_overrides', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['import_id'], ['data_imports.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_properties_owner_created', 'properties', ['owner_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_properties_postcode'), 'properties', ['postcode'], unique=False)
    op.create_table('analyses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('property_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('inputs', sa.JSON(), nullable=False),
    sa.Column('results', sa.JSON(), nullable=False),
    sa.Column('engine_version', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_analyses_owner_created', 'analyses', ['owner_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_analyses_property_id'), 'analyses', ['property_id'], unique=False)
    op.create_table('comparison_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('comparison_id', sa.Uuid(), nullable=False),
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comparison_id'], ['comparisons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comparison_id', 'property_id')
    )
    op.create_index(op.f('ix_comparison_items_comparison_id'), 'comparison_items', ['comparison_id'], unique=False)
    op.create_table('watchlist_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('watchlist_id', sa.Uuid(), nullable=False),
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('watchlist_id', 'property_id')
    )
    op.create_index(op.f('ix_watchlist_items_watchlist_id'), 'watchlist_items', ['watchlist_id'], unique=False)
    op.create_table('ai_explanations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_explanations_analysis_id'), 'ai_explanations', ['analysis_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('analysis_id', sa.Uuid(), nullable=True),
    sa.Column('comparison_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['comparison_id'], ['comparisons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_owner_id'), 'reports', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_owner_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_ai_explanations_analysis_id'), table_name='ai_explanations')
    op.drop_table('ai_explanations')
    op.drop_index(op.f('ix_watchlist_items_watchlist_id'), table_name='watchlist_items')
    op.drop_table('watchlist_items')
    op.drop_index(op.f('ix_comparison_items_comparison_id'), table_name='comparison_items')
    op.drop_table('comparison_items')
    op.drop_index(op.f('ix_analyses_property_id'), table_name='analyses')
    op.drop_index('ix_analyses_owner_created', table_name='analyses')
    op.drop_table('analyses')
    op.drop_index(op.f('ix_properties_postcode'), table_name='properties')
    op.drop_index('ix_properties_owner_created', table_name='properties')
    op.drop_table('properties')
    op.drop_index(op.f('ix_price_paid_transactions_date_of_transfer'), table_name='price_paid_transactions')
    op.drop_index('ix_ppd_sector_date', table_name='price_paid_transactions')
    op.drop_index('ix_ppd_local_authority', table_name='price_paid_transactions')
    op.drop_index('ix_ppd_district_date', table_name='price_paid_transactions')
    op.drop_table('price_paid_transactions')
    op.drop_index(op.f('ix_watchlists_owner_id'), table_name='watchlists')
    op.drop_table('watchlists')
    op.drop_index(op.f('ix_data_imports_owner_id'), table_name='data_imports')
    op.drop_table('data_imports')
    op.drop_index(op.f('ix_comparisons_owner_id'), table_name='comparisons')
    op.drop_table('comparisons')
    op.drop_index(op.f('ix_assumption_profiles_owner_id'), table_name='assumption_profiles')
    op.drop_table('assumption_profiles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
