from __future__ import annotations

import logging
from typing import Any

from app.core.config import Settings

from .base import ExplanationProvider, ExplanationResult, find_unverified_figures
from .providers import AnthropicProvider, OpenAICompatibleProvider, ProviderError, RuleBasedProvider

log = logging.getLogger(__name__)


def configured_provider(settings: Settings) -> ExplanationProvider | None:
    if settings.ai_provider == "anthropic" and settings.anthropic_api_key:
        return AnthropicProvider(settings.anthropic_api_key, settings.anthropic_model, settings.ai_timeout_seconds)
    if settings.ai_provider == "openai" and settings.openai_api_key:
        return OpenAICompatibleProvider(
            settings.openai_api_key,
            settings.openai_base_url,
            settings.openai_model,
            settings.ai_timeout_seconds,
        )
    return None


def build_context(analysis: dict[str, Any], prop: dict[str, Any] | None, extras: dict[str, Any]) -> dict:
    """The only data an explanation provider sees."""
    metrics = {
        m["key"]: {"label": m["label"], "value": m["value"], "unit": m["unit"], "basis": m["basis"]}
        for m in analysis["metrics"]
    }
    return {
        "property": prop or {"note": "ad-hoc calculation, no property record"},
        "inputs": analysis["inputs"],
        "metrics": metrics,
        "transaction_tax": {
            "name": analysis["transaction_tax"]["name"],
            "total": analysis["transaction_tax"]["total"],
        },
        "sale": analysis["sale"],
        "warnings": analysis["warnings"][:8],
        **extras,
    }


def explain(
    context: dict[str, Any], settings: Settings, provider: ExplanationProvider | None = None
) -> ExplanationResult:
    provider = provider or configured_provider(settings)
    fallback = RuleBasedProvider()
    if provider is None:
        return ExplanationResult(
            provider=fallback.name,
            model=fallback.model,
            content=fallback.generate(context),
            notice="No AI provider is configured, so this explanation was generated by deterministic rules.",
        )
    try:
        content = provider.generate(context)
    except ProviderError as e:
        log.warning("AI provider %s failed: %s", provider.name, e)
        return ExplanationResult(
            provider=fallback.name,
            model=fallback.model,
            content=fallback.generate(context),
            notice=f"The AI provider was unavailable ({e}); showing the rule-based explanation instead.",
        )
    return ExplanationResult(
        provider=provider.name,
        model=provider.model,
        content=content,
        unverified_figures=find_unverified_figures(content, context),
    )
