"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { toast } from "sonner";

import { AnalysisBody, HeadlineFigures, Warnings } from "@/components/analysis-view";
import { ErrorState, LoadingRows, Notice, PageHeader, Section } from "@/components/common";
import { Button } from "@/components/ui/button";
import { api, ApiError, download } from "@/lib/api";
import { dateTime } from "@/lib/format";
import type { Analysis, Explanation, Property, Report } from "@/lib/types";
import { cn } from "@/lib/utils";

export default function AnalysisPage() {
  const { id } = useParams<{ id: string }>();
  const router = useRouter();
  const qc = useQueryClient();
  const q = useQuery({ queryKey: ["analysis", id], queryFn: () => api<Analysis>(`/analyses/${id}`) });
  const prop = useQuery({
    queryKey: ["property", q.data?.property_id],
    queryFn: () => api<Property>(`/properties/${q.data!.property_id}`),
    enabled: Boolean(q.data?.property_id),
  });

  const report = useMutation({
    mutationFn: async (kind: "pdf" | "csv") => {
      const r = await api<Report>(`/analyses/${id}/reports?kind=${kind}`, { method: "POST" });
      await download(`/reports/${r.id}/download`, r.filename);
      return r;
    },
    onSuccess: (r) => {
      qc.invalidateQueries({ queryKey: ["reports"] });
      toast.success(`${r.kind.toUpperCase()} report downloaded and saved to Reports`);
    },
    onError: (e) => toast.error(e instanceof ApiError ? e.summary : "Could not create the report"),
  });
  const remove = useMutation({
    mutationFn: () => api(`/analyses/${id}`, { method: "DELETE" }),
    onSuccess: () => {
      qc.invalidateQueries();
      router.push(q.data?.property_id ? `/properties/${q.data.property_id}` : "/dashboard");
    },
  });

  if (q.isLoading) return <LoadingRows rows={10} />;
  if (q.error) return <ErrorState error={q.error} retry={() => q.refetch()} />;
  const a = q.data!;
  const r = a.results;

  return (
    <>
      <PageHeader
        title={a.name}
        description={
          <>
            Saved {dateTime(a.created_at)}
            {prop.data && (
              <>
                {" "}for{" "}
                <Link href={`/properties/${prop.data.id}`} className="font-medium text-wood underline underline-offset-2">
                  {prop.data.title}
                </Link>
              </>
            )}
            . Figures use the assumptions at that time.
          </>
        }
        actions={
          <>
            <Button onClick={() => report.mutate("pdf")} disabled={report.isPending}>
              Download PDF report
            </Button>
            <Button variant="outline" onClick={() => report.mutate("csv")} disabled={report.isPending}>
              Export CSV
            </Button>
            <Button
              variant="ghost"
              onClick={() => {
                if (confirm("Delete this saved analysis?")) remove.mutate();
              }}
            >
              Delete
            </Button>
          </>
        }
      />
      {prop.data?.is_demo && (
        <Notice tone="warn" className="mb-6">
          Based on a demo property: the price and rent are illustrative, so treat these results as an example.
        </Notice>
      )}
      <HeadlineFigures r={r} />
      <Warnings r={r} />
      <ExplanationPanel analysisId={a.id} />
      <AnalysisBody r={r} />
    </>
  );
}

function ExplanationPanel({ analysisId }: { analysisId: string }) {
  const qc = useQueryClient();
  const status = useQuery({ queryKey: ["ai-status"], queryFn: () => api<{ configured: boolean; provider: string; model: string }>("/ai/status") });
  const list = useQuery({ queryKey: ["explanations", analysisId], queryFn: () => api<Explanation[]>(`/analyses/${analysisId}/explanations`) });
  const create = useMutation({
    mutationFn: () => api<Explanation>(`/analyses/${analysisId}/explanations`, { method: "POST" }),
    onSuccess: () => qc.invalidateQueries({ queryKey: ["explanations", analysisId] }),
    onError: (e) => toast.error(e instanceof ApiError ? e.summary : "Could not generate an explanation"),
  });
  const latest = list.data?.[0];
  const aiOn = status.data?.configured;

  return (
    <Section
      title="Explanation"
      className="mt-8"
      description={
        aiOn
          ? `Written by ${status.data?.model} from the calculated figures only. Numbers it uses are checked against the calculation.`
          : "No AI provider is configured, so explanations are generated by transparent rules from the calculated figures."
      }
      aside={
        <Button variant={latest ? "outline" : "default"} onClick={() => create.mutate()} disabled={create.isPending}>
          {create.isPending ? "Writing…" : latest ? "Regenerate" : "Explain this deal"}
        </Button>
      }
    >
      {!latest ? (
        <p className="rounded-lg border border-dashed border-input px-4 py-5 text-sm text-slate">
          Get a plain-English read of the strengths, weaknesses, risks and what would need to change.
        </p>
      ) : (
        <div className="rounded-xl border border-rule bg-card p-5">
          {latest.content.notice && <p className="mb-3 text-xs text-slate">{latest.content.notice}</p>}
          {latest.content.unverified_figures?.length > 0 && (
            <Notice tone="warn" className="mb-4" title="Some figures could not be matched to the calculation">
              Treat these with caution: {latest.content.unverified_figures.join(", ")}.
            </Notice>
          )}
          <p className="max-w-3xl text-[15px] leading-relaxed text-ink">{latest.content.summary}</p>
          <div className="mt-5 grid gap-6 md:grid-cols-2">
            <ListBlock title="Strengths" items={latest.content.strengths} />
            <ListBlock title="Weaknesses" items={latest.content.weaknesses} />
          </div>
          <div className="mt-6">
            <h3 className="text-sm font-semibold text-slate">Risks</h3>
            <ul className="mt-2 divide-y divide-rule">
              {latest.content.risks.map((risk) => (
                <li key={risk.title} className="flex gap-3 py-2 text-sm">
                  <span
                    className={cn(
                      "mt-0.5 h-fit shrink-0 rounded-sm px-1.5 py-px text-[11px] font-semibold",
                      risk.severity === "high" && "bg-brick-soft text-brick",
                      risk.severity === "medium" && "bg-ochre-soft text-ochre",
                      risk.severity === "low" && "bg-muted text-slate",
                    )}
                  >
                    {risk.severity}
                  </span>
                  <span>
                    <strong className="font-semibold">{risk.title}.</strong> {risk.detail}
                  </span>
                </li>
              ))}
            </ul>
          </div>
          <div className="mt-6 grid gap-6 md:grid-cols-2">
            <div>
              <h3 className="text-sm font-semibold text-slate">Yield and cash flow</h3>
              <p className="mt-1.5 text-sm leading-relaxed">{latest.content.yield_and_cash_flow}</p>
              <h3 className="mt-4 text-sm font-semibold text-slate">Sensitivity</h3>
              <p className="mt-1.5 text-sm leading-relaxed">{latest.content.sensitivity}</p>
            </div>
            <ListBlock title="What would make it more attractive" items={latest.content.improvements} />
          </div>
          <p className="mt-5 border-t border-rule pt-3 text-xs text-slate">
            {latest.provider === "rule_based" ? "Rule-based explanation" : `Generated by ${latest.provider} (${latest.model})`} on{" "}
            {dateTime(latest.created_at)}. {latest.content.caveats.join(" ")}
          </p>
        </div>
      )}
    </Section>
  );
}

function ListBlock({ title, items }: { title: string; items: string[] }) {
  return (
    <div>
      <h3 className="text-sm font-semibold text-slate">{title}</h3>
      <ul className="mt-1.5 list-disc space-y-1 pl-4 text-sm leading-relaxed">
        {items.map((i) => (
          <li key={i}>{i}</li>
        ))}
      </ul>
    </div>
  );
}
